name: Deploy

run-name: 'ðŸ”¥ Deploy'

on: workflow_dispatch

permissions:
  actions: 'read'
  security-events: 'write'
  contents: 'write'
  checks: 'write'
  issues: 'write'
  pull-requests: 'write'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683


